// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/jukylin/nx/txmsg/domain/entity"

	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"
)

// MsgInfoRepo is an autogenerated mock type for the MsgInfoRepo type
type MsgInfoRepo struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, msgInfo
func (_m *MsgInfoRepo) Create(ctx context.Context, msgInfo *entity.MsgInfo) int {
	ret := _m.Called(ctx, msgInfo)

	var r0 int
	if rf, ok := ret.Get(0).(func(context.Context, *entity.MsgInfo) int); ok {
		r0 = rf(ctx, msgInfo)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// CreateByTx provides a mock function with given fields: ctx, tx, msgInfo
func (_m *MsgInfoRepo) CreateByTx(ctx context.Context, tx *gorm.DB, msgInfo *entity.MsgInfo) int {
	ret := _m.Called(ctx, tx, msgInfo)

	var r0 int
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *entity.MsgInfo) int); ok {
		r0 = rf(ctx, tx, msgInfo)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// DelSendedMsg provides a mock function with given fields: ctx, num
func (_m *MsgInfoRepo) DelSendedMsg(ctx context.Context, num int) int64 {
	ret := _m.Called(ctx, num)

	var r0 int64
	if rf, ok := ret.Get(0).(func(context.Context, int) int64); ok {
		r0 = rf(ctx, num)
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}

// FindById provides a mock function with given fields: ctx, id
func (_m *MsgInfoRepo) FindById(ctx context.Context, id int64) entity.MsgInfo {
	ret := _m.Called(ctx, id)

	var r0 entity.MsgInfo
	if rf, ok := ret.Get(0).(func(context.Context, int64) entity.MsgInfo); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(entity.MsgInfo)
	}

	return r0
}

// GetWaitingMsg provides a mock function with given fields: ctx, num
func (_m *MsgInfoRepo) GetWaitingMsg(ctx context.Context, num int) entity.MsgInfos {
	ret := _m.Called(ctx, num)

	var r0 entity.MsgInfos
	if rf, ok := ret.Get(0).(func(context.Context, int) entity.MsgInfos); ok {
		r0 = rf(ctx, num)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(entity.MsgInfos)
		}
	}

	return r0
}

// UpdateByIds provides a mock function with given fields: ctx, tx, update, ids
func (_m *MsgInfoRepo) UpdateByIds(ctx context.Context, tx *gorm.DB, update map[string]interface{}, ids []int64) int64 {
	ret := _m.Called(ctx, tx, update, ids)

	var r0 int64
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, map[string]interface{}, []int64) int64); ok {
		r0 = rf(ctx, tx, update, ids)
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}

// UpdateStatusById provides a mock function with given fields: ctx, id
func (_m *MsgInfoRepo) UpdateStatusById(ctx context.Context, id int64) int64 {
	ret := _m.Called(ctx, id)

	var r0 int64
	if rf, ok := ret.Get(0).(func(context.Context, int64) int64); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}
