// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	entity "github.com/jukylin/nx/txmsg/domain/entity"

	mock "github.com/stretchr/testify/mock"
)

// LocalQueue is an autogenerated mock type for the LocalQueue type
type LocalQueue struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *LocalQueue) Close() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Consumer provides a mock function with given fields: _a0
func (_m *LocalQueue) Consumer(_a0 func(interface{})) bool {
	ret := _m.Called(_a0)

	var r0 bool
	if rf, ok := ret.Get(0).(func(func(interface{})) bool); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// DroppedItem provides a mock function with given fields: _a0
func (_m *LocalQueue) DroppedItem(_a0 interface{}) {
	_m.Called(_a0)
}

// Produce provides a mock function with given fields: _a0
func (_m *LocalQueue) Produce(_a0 entity.Msg) bool {
	ret := _m.Called(_a0)

	var r0 bool
	if rf, ok := ret.Get(0).(func(entity.Msg) bool); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
